export enum Events {
  APPLICATION_LOADED="APPLICATION_LOADED",
  CHOOSE_QUESTION_PAGE="CHOOSE_QUESTION_PAGE",
  QUIZ_TYPE="QUIZ_TYPE",
  CATEGORY="CATEGORY",
  RESULT="RESULT",
  SEARCH_INPUT="SEARCH_INPUT",
  DEVICE = "DEVICE",

}
